import { sql } from "@vercel/postgres";
import { NextResponse } from "next/server";

// ="("&A1&","&B1&","&C1&","'",D1,"'","&E1&"),"

export async function GET(request) {
	try {
		await sql`SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
AND table_type = 'BASE TABLE';`;
	} catch (error) {
		return NextResponse.json({ error }, { status: 500 });
	}

	const pets = await sql`SELECT count(*) FROM OrderDetails; `;
	return NextResponse.json({ pets }, { status: 200 });
}

// DATABASE SOURCE: https://www.w3schools.com/sql/trysql.asp?filename=trysql_select_columns

const productsTableRows = `INSERT INTO Products (ProductName, SupplierID, CategoryID, Unit, Price)
VALUES
('Chang', 1, 1, '24 - 12 oz bottles', 19),
('Aniseed Syrup', 1, 2, '12 - 550 ml bottles', 10),
('Chef Anton''s Cajun Seasoning', 2, 2, '48 - 6 oz jars', 22),
('Chef Anton''s Gumbo Mix', 2, 2, '36 boxes', 21.35),
('Grandma''s Boysenberry Spread', 3, 2, '12 - 8 oz jars', 25),
('Uncle Bob''s Organic Dried Pears', 3, 7, '12 - 1 lb pkgs.', 30),
('Northwoods Cranberry Sauce', 3, 2, '12 - 12 oz jars', 40),
('Mishi Kobe Niku', 4, 6, '18 - 500 g pkgs.', 97),
('Ikura', 4, 8, '12 - 200 ml jars', 31),
('Queso Cabrales', 5, 4, '1 kg pkg.', 21),
('Queso Manchego La Pastora', 5, 4, '10 - 500 g pkgs.', 38),
('Konbu', 6, 8, '2 kg box', 6),
('Tofu', 6, 7, '40 - 100 g pkgs.', 23.25),
('Genen Shouyu', 6, 2, '24 - 250 ml bottles', 15.5),
('Pavlova', 7, 3, '32 - 500 g boxes', 17.45),
('Alice Mutton', 7, 6, '20 - 1 kg tins', 39),
('Carnarvon Tigers', 7, 8, '16 kg pkg.', 62.5),
('Teatime Chocolate Biscuits', 8, 3, '10 boxes x 12 pieces', 9.2),
('Sir Rodney''s Marmalade', 8, 3, '30 gift boxes', 81),
('Sir Rodney''s Scones', 8, 3, '24 pkgs. x 4 pieces', 10),
('Gustaf''s Knäckebröd', 9, 5, '24 - 500 g pkgs.', 21),
('Tunnbröd', 9, 5, '12 - 250 g pkgs.', 9),
('Guaraná Fantástica', 10, 1, '12 - 355 ml cans', 4.5),
('NuNuCa Nuß-Nougat-Creme', 11, 3, '20 - 450 g glasses', 14),
('Gumbär Gummibärchen', 11, 3, '100 - 250 g bags', 31.23),
('Schoggi Schokolade', 11, 3, '100 - 100 g pieces', 43.9),
('Rössle Sauerkraut', 12, 7, '25 - 825 g cans', 45.6),
('Thüringer Rostbratwurst', 12, 6, '50 bags x 30 sausgs.', 123.79),
('Nord-Ost Matjeshering', 13, 8, '10 - 200 g glasses', 25.89),
('Gorgonzola Telino', 14, 4, '12 - 100 g pkgs', 12.5),
('Mascarpone Fabioli', 14, 4, '24 - 200 g pkgs.', 32),
('Geitost', 15, 4, '500 g', 2.5),
('Sasquatch Ale', 16, 1, '24 - 12 oz bottles', 14),
('Steeleye Stout', 16, 1, '24 - 12 oz bottles', 18),
('Inlagd Sill', 17, 8, '24 - 250 g jars', 19),
('Gravad lax', 17, 8, '12 - 500 g pkgs.', 26),
('Côte de Blaye', 18, 1, '12 - 75 cl bottles', 263.5),
('Chartreuse verte', 18, 1, '750 cc per bottle', 18),
('Boston Crab Meat', 19, 8, '24 - 4 oz tins', 18.4),
('Jack''s New England Clam Chowder', 19, 8, '12 - 12 oz cans', 9.65),
('Singaporean Hokkien Fried Mee', 20, 5, '32 - 1 kg pkgs.', 14),
('Ipoh Coffee', 20, 1, '16 - 500 g tins', 46),
('Gula Malacca', 20, 2, '20 - 2 kg bags', 19.45),
('Røgede sild', 21, 8, '1k pkg.', 9.5),
('Spegesild', 21, 8, '4 - 450 g glasses', 12),
('Zaanse koeken', 22, 3, '10 - 4 oz boxes', 9.5),
('Chocolade', 22, 3, '10 pkgs.', 12.75),
('Maxilaku', 23, 3, '24 - 50 g pkgs.', 20),
('Valkoinen suklaa', 23, 3, '12 - 100 g bars', 16.25),
('Manjimup Dried Apples', 24, 7, '50 - 300 g pkgs.', 53),
('Filo Mix', 24, 5, '16 - 2 kg boxes', 7),
('Perth Pasties', 24, 6, '48 pieces', 32.8),
('Tourtière', 25, 6, '16 pies', 7.45),
('Pâté chinois', 25, 6, '24 boxes x 2 pies', 24),
('Gnocchi di nonna Alice', 26, 5, '24 - 250 g pkgs.', 38),
('Ravioli Angelo', 26, 5, '24 - 250 g pkgs.', 19.5),
('Escargots de Bourgogne', 27, 8, '24 pieces', 13.25),
('Raclette Courdavault', 28, 4, '5 kg pkg.', 55),
('Camembert Pierrot', 28, 4, '15 - 300 g rounds', 34),
('Sirop d''érable', 29, 2, '24 - 500 ml bottles', 28.5),
('Tarte au sucre', 29, 3, '48 pies', 49.3),
('Vegie-spread', 7, 2, '15 - 625 g jars', 43.9),
('Wimmers gute Semmelknödel', 12, 5, '20 bags x 4 pieces', 33.25),
('Louisiana Fiery Hot Pepper Sauce', 2, 2, '32 - 8 oz bottles', 21.05),
('Louisiana Hot Spiced Okra', 2, 2, '24 - 8 oz jars', 17),
('Laughing Lumberjack Lager', 16, 1, '24 - 12 oz bottles', 14),
('Scottish Longbreads', 8, 3, '10 boxes x 8 pieces', 12.5),
('Gudbrandsdalsost', 15, 4, '10 kg pkg.', 36),
('Outback Lager', 7, 1, '24 - 355 ml bottles', 15),
('Fløtemysost', 15, 4, '10 - 500 g pkgs.', 21.5),
('Mozzarella di Giovanni', 14, 4, '24 - 200 g pkgs.', 34.8),
('Röd Kaviar', 17, 8, '24 - 150 g jars', 15),
('Longlife Tofu', 4, 7, '5 kg pkg.', 10),
('Rhönbräu Klosterbier', 12, 1, '24 - 0.5 l bottles', 7.75),
('Lakkalikööri', 23, 1, '500 ml', 18),
('Original Frankfurter grüne Soße', 12, 2, '12 boxes', 13);
`;

const categoriesTableRows = `INSERT INTO Categories (CategoryName, Description)
  VALUES
    ('Beverages', 'Soft drinks, coffees, teas, beers, and ales'),
    ('Condiments', 'Sweet and savory sauces, relishes, spreads, and seasonings'),
    ('Confections', 'Desserts, candies, and sweet breads'),
    ('Dairy Products', 'Cheeses'),
    ('Grains/Cereals', 'Breads, crackers, pasta, and cereal'),
    ('Meat/Poultry', 'Prepared meats'),
    ('Produce', 'Dried fruit and bean curd'),
    ('Seafood', 'Seaweed and fish');
`;

const employeesTableRows = `INSERT INTO Employees (LastName, FirstName, BirthDate, Photo, Notes)
  VALUES
    ('Davolio', 'Nancy', '12/8/1968', 'EmpID1.pic', 'Education includes a BA in psychology from Colorado State University. She also completed (The Art of the Cold Call). Nancy is a member of ''Toastmasters International''.'),
    ('Fuller', 'Andrew', '4/2/1952', 'EmpID2.pic', 'Andrew received his BTS commercial and a Ph.D. in international marketing from the University of Dallas. He is fluent in French and Italian and reads German. He joined the company as a sales representative, was promoted to sales manager and was then named vice president of sales. Andrew is a member of the Sales Management Roundtable, the Seattle Chamber of Commerce, and the Pacific Rim Importers Association.'),
    ('Leverling', 'Janet', '8/30/1952', 'EmpID3.pic', 'Janet has a BS degree in chemistry from Boston College. She has also completed a certificate program in food retailing management. Janet was hired as a sales associate and was promoted to sales representative.'),
    ('Peacock', 'Margaret', '9/19/1955', 'EmpID4.pic', 'Margaret holds a BA in English literature from Concordia College and an MA from the American Institute of Culinary Arts. She was temporarily assigned to the London office before returning to her permanent post in Seattle.'),
    ('Buchanan', 'Steven', '3/4/1965', 'EmpID5.pic', 'Steven Buchanan graduated from St. Andrews University, Scotland, with a BSC degree. Upon joining the company as a sales representative, he spent 6 months in an orientation program at the Seattle office and then returned to his permanent post in London, where he was promoted to sales manager. Mr. Buchanan has completed the courses ''Successful Telemarketing'' and ''International Sales Management''. He is fluent in French.'),
    ('Suyama', 'Michael', '7/2/1964', 'EmpID6.pic', 'Michael is a graduate of Sussex University (MA, economics) and the University of California at Los Angeles (MBA, marketing). He has also taken the courses ''Multi-Cultural Selling'' and ''Time Management for the Sales Professional''. He is fluent in Japanese and can read and write French, Portuguese, and Spanish.'),
    ('King', 'Robert', '1/29/1962', 'EmpID7.pic', 'Robert King served in the Peace Corps and traveled extensively before completing his degree in English at the University of Michigan and then joining the company. After completing a course entitled ''Selling in Europe'', he was transferred to the London office.'),
    ('Callahan', 'Laura', '11/2/1960', 'EmpID8.pic', 'Laura received a BA in psychology from the University of Washington. She has also completed a course in business French. She reads and writes French.'),
    ('Dodsworth', 'Anne', '1/27/1969', 'EmpID9.pic', 'Anne has a BA degree in English from St. Lawrence College. She is fluent in French and German.'),
    ('West', 'Adam', '7/3/1929', 'EmpID10.pic', 'An old chum');`;

const suppliersTableRows = `INSERT INTO Suppliers (SupplierName, ContactName, Address, City, PostalCode, Country, Phone)
  VALUES
    ('Exotic Liquid', 'Charlotte Cooper', '49 Gilbert St.', 'London', 'EC1 4SD', 'UK', '(171) 555-2222'),
    ('New Orleans Cajun Delights', 'Shelley Burke', 'P.O. Box 78934', 'New Orleans', '70117', 'USA', '(100) 555-4822'),
    ('Grandma Kelly''s Homestead', 'Regina Murphy', '707 Oxford Rd.', 'Ann Arbor', '48104', 'USA', '(313) 555-5735'),
    ('Tokyo Traders', 'Yoshi Nagase', '9-8 Sekimai Musashino-shi', 'Tokyo', '100', 'Japan', '(03) 3555-5011'),
    ('Cooperativa de Quesos ''Las Cabras''', 'Antonio del Valle Saavedra', 'Calle del Rosal 4', 'Oviedo', '33007', 'Spain', '(98) 598 76 54'),
    ('Mayumi''s', 'Mayumi Ohno', '92 Setsuko Chuo-ku', 'Osaka', '545', 'Japan', '(06) 431-7877'),
    ('Pavlova, Ltd.', 'Ian Devling', '74 Rose St. Moonie Ponds', 'Melbourne', '3058', 'Australia', '(03) 444-2343'),
    ('Specialty Biscuits, Ltd.', 'Peter Wilson', '29 King''s Way', 'Manchester', 'M14 GSD', 'UK', '(161) 555-4448'),
    ('PB Knäckebröd AB', 'Lars Peterson', 'Kaloadagatan 13', 'Göteborg', 'S-345 67', 'Sweden', '031-987 65 43'),
    ('Refrescos Americanas LTDA', 'Carlos Diaz', 'Av. das Americanas 12.890', 'São Paulo', '5442', 'Brazil', '(11) 555 4640'),
    ('Heli Süßwaren GmbH & Co. KG', 'Petra Winkler', 'Tiergartenstraße 5', 'Berlin', '10785', 'Germany', '(010) 9984510'),
    ('Plutzer Lebensmittelgroßmärkte AG', 'Martin Bein', 'Bogenallee 51', 'Frankfurt', '60439', 'Germany', '(069) 992755'),
    ('Nord-Ost-Fisch Handelsgesellschaft mbH', 'Sven Petersen', 'Frahmredder 112a', 'Cuxhaven', '27478', 'Germany', '(04721) 8713'),
    ('Formaggi Fortini s.r.l.', 'Elio Rossi', 'Viale Dante, 75', 'Ravenna', '48100', 'Italy', '(0544) 60323'),
    ('Norske Meierier', 'Beate Vileid', 'Hatlevegen 5', 'Sandvika', '1320', 'Norway', '(0)2-953010'),
    ('Bigfoot Breweries', 'Cheryl Saylor', '3400 - 8th Avenue Suite 210', 'Bend', '97101', 'USA', '(503) 555-9931'),
    ('Svensk Sjöföda AB', 'Michael Björn', 'Brovallavägen 231', 'Stockholm', 'S-123 45', 'Sweden', '08-123 45 67'),
    ('Aux joyeux ecclésiastiques', 'Guylène Nodier', '203, Rue des Francs-Bourgeois', 'Paris', '75004', 'France', '(1) 03.83.00.68'),
    ('New England Seafood Cannery', 'Robb Merchant', 'Order Processing Dept. 2100 Paul Revere Blvd.', 'Boston', '2134', 'USA', '(617) 555-3267'),
    ('Leka Trading', 'Chandra Leka', '471 Serangoon Loop, Suite #402', 'Singapore', '512', 'Singapore', '555-8787'),
    ('Lyngbysild', 'Niels Petersen', 'Lyngbysild Fiskebakken 10', 'Lyngby', '2800', 'Denmark', '43844108'),
    ('Zaanse Snoepfabriek', 'Dirk Luchte', 'Verkoop Rijnweg 22', 'Zaandam', '9999 ZZ', 'Netherlands', '(12345) 1212'),
    ('Karkki Oy', 'Anne Heikkonen', 'Valtakatu 12', 'Lappeenranta', '53120', 'Finland', '(953) 10956'),
    ('G''day, Mate', 'Wendy Mackenzie', '170 Prince Edward Parade Hunter''s Hill', 'Sydney', '2042', 'Australia', '(02) 555-5914'),
    ('Ma Maison', 'Jean-Guy Lauzon', '2960 Rue St. Laurent', 'Montréal', 'H1J 1C3', 'Canada', '(514) 555-9022'),
    ('Pasta Buttini s.r.l.', 'Giovanni Giudici', 'Via dei Gelsomini, 153', 'Salerno', '84100', 'Italy', '(089) 6547665'),
    ('Escargots Nouveaux', 'Marie Delamare', '22, rue H. Voiron', 'Montceau', '71300', 'France', '85.57.00.07'),
    ('Gai pâturage', 'Eliane Noz', 'Bat. B 3, rue des Alpes', 'Annecy', '74000', 'France', '38.76.98.06'),
    ('Forêts d''érables', 'Chantal Goulet', '148 rue Chasseur', 'Ste-Hyacinthe', 'J2S 7S8', 'Canada', '(514) 555-2955');
`;

// const shippersTableTrows = `INSERT INTO Shippers (ShipperName, Phone)
//                             VALUES
//                           ('Speedy Express', '(503) 555-9831'),
//                           ('United Package', '(503) 555-3199'),
//                           ('Federal Shipping', '(503) 555-9931');`;

const customersTableRows = `INSERT INTO Customers (CustomerName, ContactName, Address, City, PostalCode, Country)
        VALUES
    ('Antonio Moreno Taquería','Antonio Moreno','Mataderos 2312','México D.F.','5023','Mexico'),
    ('Around the Horn','Thomas Hardy','120 Hanover Sq.','London','WA1 1DP','UK'),
    ('Berglunds snabbköp','Christina Berglund','Berguvsvägen 8','Luleå','S-958 22','Sweden'),
    ('Blauer See Delikatessen','Hanna Moos','Forsterstr. 57','Mannheim','68306','Germany'),
    ('Blondel père et fils','Frédérique Citeaux','24, place Kléber','Strasbourg','67000','France'),
    ('Bólido Comidas preparadas','Martín Sommer','C/ Araquil, 67','Madrid','28023','Spain'),
    ('Bon app''','Laurence Lebihans','12, rue des Bouchers','Marseille','13008','France'),
    ('Bottom-Dollar Marketse','Elizabeth Lincoln','23 Tsawassen Blvd.','Tsawassen','T2F 8M4','Canada'),
    ('B''s Beverages','Victoria Ashworth','Fauntleroy Circus','London','EC2 5NT','UK'),
    ('Cactus Comidas para llevar','Patricio Simpson','Cerrito 333','Buenos Aires','1010','Argentina'),
    ('Centro comercial Moctezuma','Francisco Chang','Sierras de Granada 9993','México D.F.','5022','Mexico'),
    ('Chop-suey Chinese','Yang Wang','Hauptstr. 29','Bern','3012','Switzerland'),
    ('Comércio Mineiro','Pedro Afonso','Av. dos Lusíadas, 23','São Paulo','05432-043','Brazil'),
    ('Consolidated Holdings','Elizabeth Brown','Berkeley Gardens 12 Brewery','London','WX1 6LT','UK'),
    ('Drachenblut Delikatessend','Sven Ottlieb','Walserweg 21','Aachen','52066','Germany'),
    ('Du monde entier','Janine Labrune','67, rue des Cinquante Otages','Nantes','44000','France'),
    ('Eastern Connection','Ann Devon','35 King George','London','WX3 6FW','UK'),
    ('Ernst Handel','Roland Mendel','Kirchgasse 6','Graz','8010','Austria'),
    ('Familia Arquibaldo','Aria Cruz','Rua Orós, 92','São Paulo','05442-030','Brazil'),
    ('FISSA Fabrica Inter. Salchichas S.A.','Diego Roel','C/ Moralzarzal, 86','Madrid','28034','Spain'),
    ('Folies gourmandes','Martine Rancé','184, chaussée de Tournai','Lille','59000','France'),
    ('Folk och fä HB','Maria Larsson','Åkergatan 24','Bräcke','S-844 67','Sweden'),
    ('Frankenversand','Peter Franken','Berliner Platz 43','München','80805','Germany'),
    ('France restauration','Carine Schmitt','54, rue Royale','Nantes','44000','France'),
    ('Franchi S.p.A.','Paolo Accorti','Via Monte Bianco 34','Torino','10100','Italy'),
    ('Furia Bacalhau e Frutos do Mar','Lino Rodriguez','Jardim das rosas n. 32','Lisboa','1675','Portugal'),
    ('Galería del gastrónomo','Eduardo Saavedra','Rambla de Cataluña, 23','Barcelona','8022','Spain'),
    ('Godos Cocina Típica','José Pedro Freyre','C/ Romero, 33','Sevilla','41101','Spain'),
    ('Gourmet Lanchonetes','André Fonseca','Av. Brasil, 442','Campinas','04876-786','Brazil'),
    ('Great Lakes Food Market','Howard Snyder','2732 Baker Blvd.','Eugene','97403','USA'),
    ('GROSELLA-Restaurante','Manuel Pereira','5ª Ave. Los Palos Grandes','Caracas','1081','Venezuela'),
    ('Hanari Carnes','Mario Pontes','Rua do Paço, 67','Rio de Janeiro','05454-876','Brazil'),
    ('HILARIÓN-Abastos','Carlos Hernández','Carrera 22 con Ave. Carlos Soublette #8-35','San Cristóbal','5022','Venezuela'),
    ('Hungry Coyote Import Store','Yoshi Latimer','City Center Plaza 516 Main St.','Elgin','97827','USA'),
    ('Hungry Owl All-Night Grocers','Patricia McKenna','8 Johnstown Road','Cork','','Ireland'),
    ('Island Trading','Helen Bennett','Garden House Crowther Way','Cowes','PO31 7PJ','UK'),
    ('Königlich Essen','Philip Cramer','Maubelstr. 90','Brandenburg','14776','Germany'),
    ('La corne d''abondance','Daniel Tonini','67, avenue de l''Europe','Versailles','78000','France'),
    ('La maison d''Asie','Annette Roulet','1 rue Alsace-Lorraine','Toulouse','31000','France'),
    ('Laughing Bacchus Wine Cellars','Yoshi Tannamuri','1900 Oak St.','Vancouver','V3F 2K1','Canada'),
    ('Lazy K Kountry Store','John Steel','12 Orchestra Terrace','Walla Walla','99362','USA'),
    ('Lehmanns Marktstand','Renate Messner','Magazinweg 7','Frankfurt a.M.','60528','Germany'),
    ('Let''s Stop N Shop','Jaime Yorres','87 Polk St. Suite 5','San Francisco','94117','USA'),
    ('LILA-Supermercado','Carlos González','Carrera 52 con Ave. Bolívar #65-98 Llano Largo','Barquisimeto','3508','Venezuela'),
    ('LINO-Delicateses','Felipe Izquierdo','Ave. 5 de Mayo Porlamar','I. de Margarita','4980','Venezuela'),
    ('Lonesome Pine Restaurant','Fran Wilson','89 Chiaroscuro Rd.','Portland','97219','USA'),
    ('Magazzini Alimentari Riuniti','Giovanni Rovelli','Via Ludovico il Moro 22','Bergamo','24100','Italy'),
    ('Maison Dewey','Catherine Dewey','Rue Joseph-Bens 532','Bruxelles','B-1180','Belgium'),
    ('Mère Paillarde','Jean Fresnière','43 rue St. Laurent','Montréal','H1J 1C3','Canada'),
    ('Morgenstern Gesundkost','Alexander Feuer','Heerstr. 22','Leipzig','4179','Germany'),
    ('North/South','Simon Crowther','South House 300 Queensbridge','London','SW7 1RZ','UK'),
    ('Océano Atlántico Ltda.','Yvonne Moncada','Ing. Gustavo Moncada 8585 Piso 20-A','Buenos Aires','1010','Argentina'),
    ('Old World Delicatessen','Rene Phillips','2743 Bering St.','Anchorage','99508','USA'),
    ('Ottilies Käseladen','Henriette Pfalzheim','Mehrheimerstr. 369','Köln','50739','Germany'),
    ('Paris spécialités','Marie Bertrand','265, boulevard Charonne','Paris','75012','France'),
    ('Pericles Comidas clásicas','Guillermo Fernández','Calle Dr. Jorge Cash 321','México D.F.','5033','Mexico'),
    ('Piccolo und mehr','Georg Pipps','Geislweg 14','Salzburg','5020','Austria'),
    ('Princesa Isabel Vinhoss','Isabel de Castro','Estrada da saúde n. 58','Lisboa','1756','Portugal'),
    ('Que Delícia','Bernardo Batista','Rua da Panificadora, 12','Rio de Janeiro','02389-673','Brazil'),
    ('Queen Cozinha','Lúcia Carvalho','Alameda dos Canàrios, 891','São Paulo','05487-020','Brazil'),
    ('QUICK-Stop','Horst Kloss','Taucherstraße 10','Cunewalde','1307','Germany'),
    ('Rancho grande','Sergio Gutiérrez','Av. del Libertador 900','Buenos Aires','1010','Argentina'),
    ('Rattlesnake Canyon Grocery','Paula Wilson','2817 Milton Dr.','Albuquerque','87110','USA'),
    ('Reggiani Caseifici','Maurizio Moroni','Strada Provinciale 124','Reggio Emilia','42100','Italy'),
    ('Ricardo Adocicados','Janete Limeira','Av. Copacabana, 267','Rio de Janeiro','02389-890','Brazil'),
    ('Richter Supermarkt','Michael Holz','Grenzacherweg 237','Genève','1203','Switzerland'),
    ('Romero y tomillo','Alejandra Camino','Gran Vía, 1','Madrid','28001','Spain'),
    ('Santé Gourmet','Jonas Bergulfsen','Erling Skakkes gate 78','Stavern','4110','Norway'),
    ('Save-a-lot Markets','Jose Pavarotti','187 Suffolk Ln.','Boise','83720','USA'),
    ('Seven Seas Imports','Hari Kumar','90 Wadhurst Rd.','London','OX15 4NB','UK'),
    ('Simons bistro','Jytte Petersen','Vinbæltet 34','København','1734','Denmark'),
    ('Spécialités du monde','Dominique Perrier','25, rue Lauriston','Paris','75016','France'),
    ('Split Rail Beer & Ale','Art Braunschweiger','P.O. Box 555','Lander','82520','USA'),
    ('Suprêmes délices','Pascale Cartrain','Boulevard Tirou, 255','Charleroi','B-6000','Belgium'),
    ('The Big Cheese','Liz Nixon','89 Jefferson Way Suite 2','Portland','97201','USA'),
    ('The Cracker Box','Liu Wong','55 Grizzly Peak Rd.','Butte','59801','USA'),
    ('Toms Spezialitäten','Karin Josephs','Luisenstr. 48','Münster','44087','Germany'),
    ('Tortuga Restaurante','Miguel Angel Paolino','Avda. Azteca 123','México D.F.','5033','Mexico'),
    ('Tradição Hipermercados','Anabela Domingues','Av. Inês de Castro, 414','São Paulo','05634-030','Brazil'),
    ('Trail''s Head Gourmet Provisioners','Helvetius Nagy','722 DaVinci Blvd.','Kirkland','98034','USA'),
    ('Vaffeljernet','Palle Ibsen','Smagsløget 45','Århus','8200','Denmark'),
    ('Victuailles en stock','Mary Saveley','2, rue du Commerce','Lyon','69004','France'),
    ('Vins et alcools Chevalier','Paul Henriot','59 rue de l''Abbaye','Reims','51100','France'),
    ('Die Wandernde Kuh','Rita Müller','Adenauerallee 900','Stuttgart','70563','Germany'),
    ('Wartian Herkku','Pirkko Koskitalo','Torikatu 38','Oulu','90110','Finland'),
    ('Wellington Importadora','Paula Parente','Rua do Mercado, 12','Resende','08737-363','Brazil'),
    ('White Clover Markets','Karl Jablonski','305 - 14th Ave. S. Suite 3B','Seattle','98128','USA'),
    ('Wilman Kala','Matti Karttunen','Keskuskatu 45','Helsinki','21240','Finland'),
    ('Wolski','Zbyszek','ul. Filtrowa 68','Walla','01-012','Poland');`;
